# SoftMax는 시그모이드함수를 하는 연산
## 0~1 사이의 결과값을 출력해 원핫인코딩을 통해 결과를 예측

In [1]:
#pip install tensorflow

  Using cached tensorflow-2.4.1-cp38-cp38-win_amd64.whl (370.7 MB)
  Using cached protobuf-3.15.8-py2.py3-none-any.whl (173 kB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached grpcio-1.32.0-cp38-cp38-win_amd64.whl (2.6 MB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
  Using cached tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
  Using cached wrapt-1.12.1-cp38-cp38-win_amd64.whl
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached termcolor-1.1.0-py3-none-any.whl
  Using cached tensorflow_estimator-2.4.0-py2.py3-none-any.whl (462 kB)
  Using cached absl_py-0.12.0-py3-none-any.whl (129 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached Markdown-3.3.4-py3-none-any.whl (97 kB)
  Using cached tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
  Using cached google_auth_oauthli

distutils: C:\ProgramData\Anaconda3\Include\UNKNOWN
sysconfig: C:\ProgramData\Anaconda3\Include
user = False
home = None
root = None
prefix = None
distutils: C:\ProgramData\Anaconda3\Include\UNKNOWN
sysconfig: C:\ProgramData\Anaconda3\Include
user = False
home = None
root = None
prefix = None


In [2]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

tf.random.set_seed(777)  # for reproducibility

2.4.1


In [3]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

#convert into numpy and float format
x_data = np.asarray(x_data, dtype=np.float32)
y_data = np.asarray(y_data, dtype=np.float32)

In [4]:
#dataset을 선언합니다.
# dataset = tf.data.Dataset.from_tensor_slices((x_data, y_data))
# dataset = dataset.repeat().batch(2)

nb_classes = 3 #class의 개수입니다.

print(x_data.shape)
print(y_data.shape)

(8, 4)
(8, 3)


In [6]:
#Weight and bias setting
#random.nomal 랜덤 정규분포 생성
#4개의 특징값과 3개의 클래스를 선택
W = tf.Variable(tf.random.normal((4, nb_classes)), name='weight')
b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')
variables = [W, b]

print(W)
print(b)

<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.35265976, -0.25515324, -1.1368378 ],
       [-0.7476295 , -0.9641192 , -0.26755205],
       [ 1.2396927 , -1.0720978 , -0.96597004],
       [-1.9027146 , -0.29748687, -0.37349987]], dtype=float32)>
<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([ 1.7266569 ,  0.93108284, -0.43655586], dtype=float32)>


In [7]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
def hypothesis(X):
    return tf.nn.softmax(tf.matmul(X, W) + b)

print(hypothesis(x_data))

tf.Tensor(
[[8.9842445e-01 7.0648253e-02 3.0927293e-02]
 [9.9714017e-01 2.5916263e-03 2.6826005e-04]
 [9.6489942e-01 3.3854119e-02 1.2464090e-03]
 [9.9905068e-01 9.3302521e-04 1.6300501e-05]
 [9.7376448e-01 1.5365502e-03 2.4698945e-02]
 [9.6729952e-01 2.2433503e-02 1.0266927e-02]
 [9.9113363e-01 9.5805270e-04 7.9083163e-03]
 [9.9310726e-01 3.8139641e-04 6.5112603e-03]], shape=(8, 3), dtype=float32)


In [8]:
# Softmax onehot test
sample_db = [[8,2,1,4]]
sample_db = np.asarray(sample_db, dtype=np.float32)

print(hypothesis(sample_db))

tf.Tensor([[8.78809988e-01 1.21101834e-01 8.81008382e-05]], shape=(1, 3), dtype=float32)


In [9]:

def cost_fn(X, Y):
    logits = hypothesis(X)
    cost = -tf.reduce_sum(Y * tf.math.log(logits), axis=1)
    cost_mean = tf.reduce_mean(cost)
    
    return cost_mean

print(cost_fn(x_data, y_data))

tf.Tensor(4.4569345, shape=(), dtype=float32)


In [16]:
x = tf.constant(3.0)
print(x)
with tf.GradientTape() as g:
    g.watch(x)
    y = x * x # x^2
dy_dx = g.gradient(y, x) # Will compute to 6.0
print(dy_dx)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


In [11]:
#경사하강법
def grad_fn(X, Y):
    with tf.GradientTape() as tape:
        loss = cost_fn(X, Y)
        grads = tape.gradient(loss, variables)

        return grads

print(grad_fn(x_data, y_data))

[<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.4636137 , -0.72419554, -0.73941827],
       [ 1.6759303 , -1.2196605 , -0.45626992],
       [ 2.6729586 , -1.835885  , -0.8370737 ],
       [ 2.789841  , -1.9541732 , -0.83566797]], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.72310245, -0.35833293, -0.36476952], dtype=float32)>]


In [12]:
#학습
def fit(X, Y, epochs=2000, verbose=100):
    optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1)

    for i in range(epochs):
        grads = grad_fn(X, Y)
        optimizer.apply_gradients(zip(grads, variables))
        if (i==0) | ((i+1)%verbose==0):
            print('Loss at epoch %d: %f' %(i+1, cost_fn(X, Y).numpy()))
            
fit(x_data, y_data)

Loss at epoch 1: 2.472669
Loss at epoch 100: 0.639449
Loss at epoch 200: 0.524868
Loss at epoch 300: 0.463929
Loss at epoch 400: 0.416869
Loss at epoch 500: 0.375229
Loss at epoch 600: 0.335701
Loss at epoch 700: 0.296750
Loss at epoch 800: 0.261106
Loss at epoch 900: 0.242689
Loss at epoch 1000: 0.229923
Loss at epoch 1100: 0.218464
Loss at epoch 1200: 0.208102
Loss at epoch 1300: 0.198676
Loss at epoch 1400: 0.190059
Loss at epoch 1500: 0.182147
Loss at epoch 1600: 0.174857
Loss at epoch 1700: 0.168117
Loss at epoch 1800: 0.161866
Loss at epoch 1900: 0.156053
Loss at epoch 2000: 0.150633


## prediction check

In [13]:
sample_data = [[2,1,3,2]] # answer_label [[0,0,1]]
sample_data = np.asarray(sample_data, dtype=np.float32)

a = hypothesis(sample_data)

print(a)
print(tf.argmax(a, 1)) #index: 2

tf.Tensor([[0.00299491 0.08320002 0.91380507]], shape=(1, 3), dtype=float32)
tf.Tensor([2], shape=(1,), dtype=int64)


In [14]:
b = hypothesis(x_data)
print(b)
print(tf.argmax(b, 1))
print(tf.argmax(y_data, 1)) # matches with y_data

tf.Tensor(
[[3.9244078e-06 1.0612481e-03 9.9893481e-01]
 [2.9949085e-03 8.3200000e-02 9.1380507e-01]
 [2.8073552e-08 1.6109987e-01 8.3890009e-01]
 [8.4767669e-07 8.5104239e-01 1.4895685e-01]
 [2.4318270e-01 7.4461037e-01 1.2206920e-02]
 [1.2708341e-01 8.7290496e-01 1.1621861e-05]
 [7.6835233e-01 2.3162490e-01 2.2691425e-05]
 [9.2074132e-01 7.9258226e-02 3.8502526e-07]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)


## convert as class

In [15]:
class softmax_classifer(tf.keras.Model):
    def __init__(self, nb_classes):
        super(softmax_classifer, self).__init__()
        self.W = tf.Variable(tf.random.normal((4, nb_classes)), name='weight')
        self.b = tf.Variable(tf.random.normal((nb_classes,)), name='bias')
        
    def softmax_regression(self, X):
        return tf.nn.softmax(tf.matmul(X, self.W) + self.b)
    
    def cost_fn(self, X, Y):
        logits = self.softmax_regression(X)
        cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(logits), axis=1))        
        return cost
    
    def grad_fn(self, X, Y):
        with tf.GradientTape() as tape:
            cost = self.cost_fn(x_data, y_data)
            grads = tape.gradient(cost, self.variables)            
            return grads
    
    def fit(self, X, Y, epochs=2000, verbose=500):
        optimizer =  tf.keras.optimizers.SGD(learning_rate=0.1)

        for i in range(epochs):
            grads = self.grad_fn(X, Y)
            optimizer.apply_gradients(zip(grads, self.variables))
            if (i==0) | ((i+1)%verbose==0):
                print('Loss at epoch %d: %f' %(i+1, self.cost_fn(X, Y).numpy()))
            
model = softmax_classifer(nb_classes)
model.fit(x_data, y_data)

Loss at epoch 1: 9.457277
Loss at epoch 500: 0.505920
Loss at epoch 1000: 0.277469
Loss at epoch 1500: 0.204628
Loss at epoch 2000: 0.167065
